// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {history} from '../models';
import {settings} from '../models';
import {llm} from '../models';
import {context} from '../models';

export function ConfirmTool(arg1:string,arg2:boolean):Promise<void>;

export function GetSearchHistory(arg1:string):Promise<Array<history.SearchHistory>>;

export function GetSettings():Promise<settings.Settings>;

export function Greet(arg1:string):Promise<string>;

export function IsStartupComplete():Promise<boolean>;

export function SearchWithLLM(arg1:string):Promise<llm.ChatResponse>;

export function SearchWithMCP(arg1:string):Promise<void>;

export function SetVersion(arg1:string):Promise<void>;

export function Shutdown(arg1:context.Context):Promise<void>;

export function TestAPIConnection():Promise<void>;

export function UpdateSettings(arg1:settings.Settings):Promise<void>;
