// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';
import {history} from '../models';
import {settings} from '../models';
import {llm} from '../models';
import {context} from '../models';

export function AddMCPSSEServer(arg1:string,arg2:string,arg3:Array<string>):Promise<void>;

export function AddMCPSTDIOServer(arg1:string,arg2:string,arg3:Array<string>,arg4:{[key: string]: string}):Promise<void>;

export function ConfirmTool(arg1:string,arg2:boolean):Promise<void>;

export function DeleteMCPServer(arg1:string):Promise<void>;

export function DisableMCPServer(arg1:string):Promise<void>;

export function EnableMCPServer(arg1:string):Promise<void>;

export function GetActiveMCPConfigPath():Promise<string>;

export function GetMCPConfigPath():Promise<string>;

export function GetMCPServers():Promise<Array<backend.MCPServerInfo>>;

export function GetSearchHistory(arg1:string):Promise<Array<history.SearchHistory>>;

export function GetSettings():Promise<settings.Settings>;

export function Greet(arg1:string):Promise<string>;

export function IsStartupComplete():Promise<boolean>;

export function SearchWithLLM(arg1:string):Promise<llm.ChatResponse>;

export function SearchWithMCP(arg1:string):Promise<void>;

export function SetMCPServerEnabled(arg1:string,arg2:boolean):Promise<void>;

export function SetVersion(arg1:string):Promise<void>;

export function Shutdown(arg1:context.Context):Promise<void>;

export function TestAPIConnection():Promise<void>;

export function UpdateMCPSSEServer(arg1:string,arg2:string,arg3:Array<string>):Promise<void>;

export function UpdateMCPSTDIOServer(arg1:string,arg2:string,arg3:Array<string>,arg4:{[key: string]: string}):Promise<void>;

export function UpdateSettings(arg1:settings.Settings):Promise<void>;
