// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConfirmTool(arg1, arg2) {
  return window['go']['backend']['App']['ConfirmTool'](arg1, arg2);
}

export function GetSearchHistory(arg1) {
  return window['go']['backend']['App']['GetSearchHistory'](arg1);
}

export function GetSettings() {
  return window['go']['backend']['App']['GetSettings']();
}

export function Greet(arg1) {
  return window['go']['backend']['App']['Greet'](arg1);
}

export function IsStartupComplete() {
  return window['go']['backend']['App']['IsStartupComplete']();
}

export function SearchWithLLM(arg1) {
  return window['go']['backend']['App']['SearchWithLLM'](arg1);
}

export function SearchWithMCP(arg1) {
  return window['go']['backend']['App']['SearchWithMCP'](arg1);
}

export function SetVersion(arg1) {
  return window['go']['backend']['App']['SetVersion'](arg1);
}

export function Shutdown(arg1) {
  return window['go']['backend']['App']['Shutdown'](arg1);
}

export function TestAPIConnection() {
  return window['go']['backend']['App']['TestAPIConnection']();
}

export function UpdateSettings(arg1) {
  return window['go']['backend']['App']['UpdateSettings'](arg1);
}
