// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddMCPSSEServer(arg1, arg2, arg3) {
  return window['go']['backend']['App']['AddMCPSSEServer'](arg1, arg2, arg3);
}

export function AddMCPSTDIOServer(arg1, arg2, arg3, arg4) {
  return window['go']['backend']['App']['AddMCPSTDIOServer'](arg1, arg2, arg3, arg4);
}

export function ConfirmTool(arg1, arg2) {
  return window['go']['backend']['App']['ConfirmTool'](arg1, arg2);
}

export function DeleteMCPServer(arg1) {
  return window['go']['backend']['App']['DeleteMCPServer'](arg1);
}

export function DisableMCPServer(arg1) {
  return window['go']['backend']['App']['DisableMCPServer'](arg1);
}

export function EnableMCPServer(arg1) {
  return window['go']['backend']['App']['EnableMCPServer'](arg1);
}

export function GetActiveMCPConfigPath() {
  return window['go']['backend']['App']['GetActiveMCPConfigPath']();
}

export function GetMCPConfigPath() {
  return window['go']['backend']['App']['GetMCPConfigPath']();
}

export function GetMCPServers() {
  return window['go']['backend']['App']['GetMCPServers']();
}

export function GetSearchHistory(arg1) {
  return window['go']['backend']['App']['GetSearchHistory'](arg1);
}

export function GetSettings() {
  return window['go']['backend']['App']['GetSettings']();
}

export function Greet(arg1) {
  return window['go']['backend']['App']['Greet'](arg1);
}

export function IsStartupComplete() {
  return window['go']['backend']['App']['IsStartupComplete']();
}

export function SearchWithLLM(arg1) {
  return window['go']['backend']['App']['SearchWithLLM'](arg1);
}

export function SearchWithMCP(arg1) {
  return window['go']['backend']['App']['SearchWithMCP'](arg1);
}

export function SetMCPServerEnabled(arg1, arg2) {
  return window['go']['backend']['App']['SetMCPServerEnabled'](arg1, arg2);
}

export function SetVersion(arg1) {
  return window['go']['backend']['App']['SetVersion'](arg1);
}

export function Shutdown(arg1) {
  return window['go']['backend']['App']['Shutdown'](arg1);
}

export function TestAPIConnection() {
  return window['go']['backend']['App']['TestAPIConnection']();
}

export function UpdateMCPSSEServer(arg1, arg2, arg3) {
  return window['go']['backend']['App']['UpdateMCPSSEServer'](arg1, arg2, arg3);
}

export function UpdateMCPSTDIOServer(arg1, arg2, arg3, arg4) {
  return window['go']['backend']['App']['UpdateMCPSTDIOServer'](arg1, arg2, arg3, arg4);
}

export function UpdateSettings(arg1) {
  return window['go']['backend']['App']['UpdateSettings'](arg1);
}
