name: Release
on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: windows-latest
            platform: windows/amd64
            artifact_name: Smart-Spotlight-AI.exe
            asset_name: smart-spotlight-ai-windows-amd64.exe
          - os: windows-latest
            platform: windows/arm64
            artifact_name: Smart-Spotlight-AI.exe
            asset_name: smart-spotlight-ai-windows-arm64.exe
          - os: macos-latest
            platform: darwin/universal
            artifact_name: Smart-Spotlight-AI
            asset_name: smart-spotlight-ai-mac-universal
          - os: ubuntu-latest
            platform: linux/amd64
            artifact_name: Smart-Spotlight-AI
            asset_name: smart-spotlight-ai-linux-amd64

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '>=1.21.0'

      - name: Get Version
        id: get_version
        run: |
          VERSION=$(cat wails.json | jq -r .info.productVersion)
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"
        shell: bash

      - name: Install dependencies
        run: |
          go install github.com/wailsapp/wails/v2/cmd/wails@latest
          cd frontend && npm install

      - name: Build
        run: |
          wails build -platform ${{ matrix.platform }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.asset_name }}
          path: build/bin/${{ matrix.artifact_name }}

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Get Version
        id: get_version
        run: |
          VERSION=$(cat wails.json | jq -r .info.productVersion)
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"
        shell: bash

      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          path: artifacts

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.get_version.outputs.version }}
          release_name: Release v${{ steps.get_version.outputs.version }}
          draft: false
          prerelease: false

      - name: Upload Release Assets (Windows AMD64)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./artifacts/smart-spotlight-ai-windows-amd64.exe/Smart-Spotlight-AI.exe
          asset_name: smart-spotlight-ai-windows-amd64.exe
          asset_content_type: application/octet-stream

      - name: Upload Release Assets (Windows ARM64)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./artifacts/smart-spotlight-ai-windows-arm64.exe/Smart-Spotlight-AI.exe
          asset_name: smart-spotlight-ai-windows-arm64.exe
          asset_content_type: application/octet-stream

      - name: Upload Release Assets (macOS Universal)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./artifacts/smart-spotlight-ai-mac-universal/Smart-Spotlight-AI
          asset_name: smart-spotlight-ai-mac-universal
          asset_content_type: application/octet-stream

      - name: Upload Release Assets (Linux)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./artifacts/smart-spotlight-ai-linux-amd64/Smart-Spotlight-AI
          asset_name: smart-spotlight-ai-linux-amd64
          asset_content_type: application/octet-stream