name: Release
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '>=1.21.0'
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install Task
        run: sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b /usr/local/bin

      - name: Install Wails
        run: go install github.com/wailsapp/wails/v2/cmd/wails@latest

      - name: Get Version
        id: get_version
        run: |
          VERSION=$(cat wails.json | jq -r .info.productVersion)
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"
        shell: bash

      - name: Install Dependencies and Build All Platforms
        run: |
          task deps
          task package

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.get_version.outputs.version }}
          name: Release v${{ steps.get_version.outputs.version }}
          draft: false
          prerelease: false
          files: |
            build/smart-spotlight-wails-windows-amd64.exe
            build/smart-spotlight-wails-mac-universal.app
            build/smart-spotlight-wails-linux-amd64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}